config/routes.rb
Rails.application.routes.draw do
  resources :eventos, path_names: { new: 'novo', edit: 'editar'}
  resources :contas_a_receber, path_names: { new: 'nova', edit: 'editar'}
  resources :contas_a_pagar, path_names: { new: 'nova', edit: 'editar'}
  resources :temas, path_names: { new: 'novo', edit: 'editar'}
  resources :fornecedores, path_names: { new: 'novo', edit: 'editar'}
  resources :categorias, path_names: { new: 'nova', edit: 'editar'}
  resources :clientes, path_names: { new: 'novo', edit: 'editar'}

  get 'estados/:id/cidades' => 'estados#cidades', as: :cidades_do_estado

  get 'contas_a_receber/evento/:id' => 'contas_a_receber#evento', as: :contas_a_receber_do_evento

  root 'eventos#index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  belongs_to :estado
  belongs_to :cidade

  has_many :eventos, dependent: :destroy
  has_many :contas_a_receber

  validates :nome, :estado, :cidade, presence: :true

end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
    @cidades = @cliente.try(:estado).try(:cidades)
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente foi cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente foi excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :conjuge, :endereco, :bairro, :cep, :estado_id, :cidade_id, :tresidencial, :tcelular, :cpf, :rg )
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <fieldset>
    <legend>Identificação</legend>
      <div class="row">
        <div class="small-12 medium-6 columns">
          <%= f.label :nome, 'Nome' %> <br>
          <%= f.text_field :nome %>
        </div>

        <div class="small-12 medium-6 columns">
          <%= f.label :conjuge, 'Conjuge' %> <br>
          <%= f.text_field :conjuge %>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>Endereço</legend>
      <div class="row">
        <div class="small-12 medium-6 columns">
          <%= f.label :endereco, 'Logradouro' %> <br>
          <%= f.text_field :endereco %>
        </div>

        <div class="small-12 medium-3 columns">
          <%= f.label :bairro, 'Bairro' %><br>
          <%= f.text_field :bairro %>
        </div>

        <div class="small-12 medium-3 columns">
          <%= f.label :cep, 'CEP' %><br>
          <%= f.text_field :cep, class: "cliente_cep" %>

        </div>

        <div class="small-4 medium-2 columns">
          <%= f.label :estado_id, 'Estado' %> <br>
          <%= f.collection_select(:estado_id, Estado.all, :id, :nome, { prompt: 'UF' }) %>
        </div>

        <div class="small-8 medium-5 end columns">
          <%= f.label :cidade, 'Cidade' %><br>

          <% if @cliente.estado.nil? %>
          <%= raw('<select id="cliente_cidade_id" name="cliente[cidade_id]"></select>') %>
          <% else %>
          <%= f.collection_select :cidade_id, @cidades, :id, :nome,
                  { prompt: @cliente.try(:cidade).try(:nome) } %>
          <% end %>

        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>Contato</legend>
        <div class="row">
        <div class="small-12 medium-3 columns">
          <%= f.label :tresidencial, 'Telefone Residencial' %><br>
          <%= f.text_field :tresidencial, class: "cliente_tresidencial"%>
        </div>

        <div class="small-12 medium-3 end columns">
          <%= f.label :tcelular, 'Telefone Celular' %><br>
          <%= f.text_field :tcelular, class: "cliente_tcelular" %>
        </div>
      </div>
    </fieldset>
    <fieldset>
      <legend>Documentos</legend>
      <div class="row">
        <div class="small-12 medium-3 columns">
          <%= f.label :cpf, 'CPF' %><br>
          <%= f.text_field :cpf, class: "cliente_cpf" %>
        </div>

        <div class="small-12 medium-3 end columns">
          <%= f.label :rg, 'RG' %><br>
          <%= f.text_field :rg %>
        </div>
      </div>
    </fieldset>
    <div>
      <%= f.submit 'Salvar', class: 'button' %>
    </div>
<% end %>

app/views/clientes/edit.html.erb
<h1 class="text-center">Edita Cliente</h1>

<%= render 'form' %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Telefone residencial</th>
      <th>Telefone celular</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nome %></td>
        <td><%= cliente.tresidencial %></td>
        <td><%= cliente.tcelular %></td>
        <td><%= link_to 'Exibir', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Excluir', cliente, method: :delete, data: { confirm: 'Tem certeza? Esta ação irá excluir todos os eventos deste cliente.' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'Novo cliente', new_cliente_path, class: 'button', method: :get %>

app/views/clientes/new.html.erb
<h1 class="text-center">Novo Cliente</h1>

<%= render 'form' %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>
<h2 class="text-center">Cliente</h2>
<fieldset>
  <legend>Identificação</legend>
  <p>
    <strong>Nome do cliente:</strong>
    <%= @cliente.nome %>
  </p>
  <p>
    <strong>Nome do conjuge:</strong>
    <%= @cliente.conjuge %>
  </p>
</fieldset>

<fieldset>
  <legend>Endereço</legend>
  <p>
    <strong>Logradouro</strong>
    <%= @cliente.endereco %>
  </p>

  <p>
    <strong>Bairro:</strong>
    <%= @cliente.bairro %>
  </p>

  <p>
    <strong>Cep:</strong>
    <%= @cliente.cep %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= @cliente.estado.nome %>
  </p>

  <p>
    <strong>Cidade:</strong>
    <%= @cliente.cidade.nome %>
  </p>
</fieldset>

<fieldset>
  <legend>Contato</legend>
  <p>
    <strong>Telefone residencial:</strong>
    <%= @cliente.tresidencial %>
  </p>

  <p>
    <strong>Telefone celular:</strong>
    <%= @cliente.tcelular %>
  </p>
</fieldset>

<fieldset>
  <legend>Documentos</legend>
    <p>
      <strong>Cpf:</strong>
      <%= @cliente.cpf %>
    </p>

    <p>
      <strong>Rg:</strong>
      <%= @cliente.rg %>
    </p>
</fieldset>
<%= link_to 'Editar', edit_cliente_path(@cliente) %> |
<%= link_to 'Voltar', clientes_path %>