config/routes.rb
Rails.application.routes.draw do
  resources :eventos, path_names: { new: 'novo', edit: 'editar'}
  resources :contas_a_receber, path_names: { new: 'nova', edit: 'editar'}
  resources :contas_a_pagar, path_names: { new: 'nova', edit: 'editar'}
  resources :temas, path_names: { new: 'novo', edit: 'editar'}
  resources :fornecedores, path_names: { new: 'novo', edit: 'editar'}
  resources :categorias, path_names: { new: 'nova', edit: 'editar'}
  resources :clientes, path_names: { new: 'novo', edit: 'editar'}

  get 'estados/:id/cidades' => 'estados#cidades', as: :cidades_do_estado

  get 'contas_a_receber/evento/:id' => 'contas_a_receber#evento', as: :contas_a_receber_do_evento

  root 'eventos#index'

end

app/models/tema.rb
class Tema < ActiveRecord::Base
  has_many :eventos
end

app/controllers/temas_controller.rb
class TemasController < ApplicationController
  before_action :set_tema, only: [:show, :edit, :update, :destroy]

  # GET /temas
  # GET /temas.json
  def index
    @temas = Tema.all
  end

  # GET /temas/1
  # GET /temas/1.json
  def show
  end

  # GET /temas/new
  def new
    @tema = Tema.new
  end

  # GET /temas/1/edit
  def edit
  end

  # POST /temas
  # POST /temas.json
  def create
    @tema = Tema.new(tema_params)

    respond_to do |format|
      if @tema.save
        format.html { redirect_to @tema, notice: 'Tema was successfully created.' }
        format.json { render :show, status: :created, location: @tema }
      else
        format.html { render :new }
        format.json { render json: @tema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temas/1
  # PATCH/PUT /temas/1.json
  def update
    respond_to do |format|
      if @tema.update(tema_params)
        format.html { redirect_to @tema, notice: 'Tema was successfully updated.' }
        format.json { render :show, status: :ok, location: @tema }
      else
        format.html { render :edit }
        format.json { render json: @tema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temas/1
  # DELETE /temas/1.json
  def destroy
    @tema.destroy
    respond_to do |format|
      format.html { redirect_to temas_url, notice: 'Tema was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tema
      @tema = Tema.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tema_params
      params.require(:tema).permit(:nome, :obs)
    end
end

app/helpers/temas_helper.rb
module TemasHelper
end

app/views/temas/_form.html.erb
<%= form_for(@tema) do |f| %>
  <% if @tema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tema.errors.count, "error") %> prohibited this tema from being saved:</h2>

      <ul>
      <% @tema.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Identificação</legend>
      <div class="row">
        <div class="small-12 medium-6 columns">
    <%= f.label :nome, 'Nome' %><br>
    <%= f.text_field :nome %>
  </div>
  </div>


  <div class="row">
  <div class="small-12 medium-6 columns">
    <%= f.label :obs , 'Observação' %><br>
    <%= f.text_area :obs %>
  </div>
  </div>

</fieldset>


  <div>
    <%= f.submit 'Salvar' , class: 'button' %>
  </div>
<% end %>

app/views/temas/edit.html.erb
<h1 class="text-center">Edita tema</h1>

<%= render 'form' %>

app/views/temas/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Temas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Obs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @temas.each do |tema| %>
      <tr>
        <td><%= tema.nome %></td>
        <td><%= tema.obs %></td>
        <td><%= link_to 'Exibir', tema %></td>
        <td><%= link_to 'Editar', edit_tema_path(tema) %></td>
        <td><%= link_to 'Excluir', tema, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= button_to 'Novo tema', new_tema_path, class: 'button', method: :get %>

app/views/temas/new.html.erb
<h1 class="text-center">Novo Tema</h1>

<%= render 'form' %>

app/views/temas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @tema.nome %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @tema.obs %>
</p>

<%= link_to 'Edit', edit_tema_path(@tema) %> |
<%= link_to 'Back', temas_path %>