config/routes.rb
Rails.application.routes.draw do
  resources :eventos, path_names: { new: 'novo', edit: 'editar'}
  resources :contas_a_receber, path_names: { new: 'nova', edit: 'editar'}
  resources :contas_a_pagar, path_names: { new: 'nova', edit: 'editar'}
  resources :temas, path_names: { new: 'novo', edit: 'editar'}
  resources :fornecedores, path_names: { new: 'novo', edit: 'editar'}
  resources :categorias, path_names: { new: 'nova', edit: 'editar'}
  resources :clientes, path_names: { new: 'novo', edit: 'editar'}

  get 'estados/:id/cidades' => 'estados#cidades', as: :cidades_do_estado

  get 'contas_a_receber/evento/:id' => 'contas_a_receber#evento', as: :contas_a_receber_do_evento

  root 'eventos#index'

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  has_many :fornecedores
end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController
  before_action :set_categoria, only: [:show, :edit, :update, :destroy]

  # GET /categorias
  # GET /categorias.json
  def index
    @categorias = Categoria.all
  end

  # GET /categorias/1
  # GET /categorias/1.json
  def show
  end

  # GET /categorias/new
  def new
    @categoria = Categoria.new
  end

  # GET /categorias/1/edit
  def edit
  end

  # POST /categorias
  # POST /categorias.json
  def create
    @categoria = Categoria.new(categoria_params)

    respond_to do |format|
      if @categoria.save
        format.html { redirect_to @categoria, notice: 'Categoria was successfully created.' }
        format.json { render :show, status: :created, location: @categoria }
      else
        format.html { render :new }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categorias/1
  # PATCH/PUT /categorias/1.json
  def update
    respond_to do |format|
      if @categoria.update(categoria_params)
        format.html { redirect_to @categoria, notice: 'Categoria was successfully updated.' }
        format.json { render :show, status: :ok, location: @categoria }
      else
        format.html { render :edit }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorias/1
  # DELETE /categorias/1.json
  def destroy
    @categoria.destroy
    respond_to do |format|
      format.html { redirect_to categorias_url, notice: 'Categoria was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoria
      @categoria = Categoria.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categoria_params
      params.require(:categoria).permit(:tipo, :observacao)
    end
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/views/categorias/_form.html.erb
<%= form_for(@categoria) do |f| %>
  <% if @categoria.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categoria.errors.count, "error") %> prohibited this categoria from being saved:</h2>

      <ul>
      <% @categoria.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Identificação</legend>
      <div class="row">
        <div class="small-12 medium-6 columns">
    <%= f.label :tipo, 'Tipo' %><br>
    <%= f.text_field :tipo %>
  </div>
</div>

<div class="row">
  <div class="small-12 medium-6 columns">
  <%= f.label :observacao , 'Observação' %><br>
  <%= f.text_field :observacao %>
  </div>
</div>
  </fieldset>

  <div>
    <%= f.submit 'Salvar' , class: 'button' %>
  </div>
<% end %>

app/views/categorias/edit.html.erb
<h1 class="text-center">Edita Categoria</h1>

<%= render 'form' %>

app/views/categorias/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Categorias</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Observacao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categorias.each do |categoria| %>
      <tr>
        <td><%= categoria.tipo %></td>
        <td><%= categoria.observacao %></td>
        <td><%= link_to 'Exibir', categoria %></td>
        <td><%= link_to 'Editar', edit_categoria_path(categoria) %></td>
        <td><%= link_to 'Excluir', categoria, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'Nova categoria', new_categoria_path, class: 'button', method: :get %>

app/views/categorias/new.html.erb
<h1 class="text-center">Nova Categoria</h1>

<%= render 'form' %>

app/views/categorias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @categoria.tipo %>
</p>

<p>
  <strong>Observacao:</strong>
  <%= @categoria.observacao %>
</p>

<%= link_to 'Edit', edit_categoria_path(@categoria) %> |
<%= link_to 'Back', categorias_path %>